---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: full-cluster-manager
rules:
    - apiGroups: [""]
      resources: ["namespaces", "pods", "services", "endpoints"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

    - apiGroups: ["apps"]
      resources: ["deployments", "statefulsets", "daemonsets"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

    - apiGroups: ["networking.k8s.io"]
      resources: ["ingresses"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

    - apiGroups: [""]
      resources: ["pods/log", "pods/exec"]
      verbs: ["get", "list", "create"]

    - apiGroups: [""]
      resources: ["events"]
      verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: full-cluster-manager-binding
subjects:
    - kind: ServiceAccount
      name: eks-access-sa
      namespace: bones
roleRef:
    kind: ClusterRole
    name: full-cluster-manager
    apiGroup: rbac.authorization.k8s.io
