/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as IndexImport } from "./routes/index"
import { Route as WorkspaceIndexImport } from "./routes/workspace/index"
import { Route as IamIndexImport } from "./routes/iam/index"
import { Route as WorkspaceNewImport } from "./routes/workspace/new"
import { Route as WorkspaceContainersImport } from "./routes/workspace/containers"
import { Route as AuthSignupImport } from "./routes/auth/signup"
import { Route as AuthResetPasswordImport } from "./routes/auth/reset-password"
import { Route as AuthLoginImport } from "./routes/auth/login"
import { Route as AuthForgotPasswordImport } from "./routes/auth/forgot-password"
import { Route as AuthActivateImport } from "./routes/auth/activate"
import { Route as WorkspaceWorkspaceIdIndexImport } from "./routes/workspace/$workspaceId/index"
import { Route as IamUsersIndexImport } from "./routes/iam/users/index"
import { Route as WorkspaceWorkspaceIdSettingsImport } from "./routes/workspace/$workspaceId/settings"
import { Route as WorkspaceWorkspaceIdPermissionsImport } from "./routes/workspace/$workspaceId/permissions"
import { Route as IamUsersNewImport } from "./routes/iam/users/new"
import { Route as IamUsersUserIdImport } from "./routes/iam/users/$userId"

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const WorkspaceIndexRoute = WorkspaceIndexImport.update({
  id: "/workspace/",
  path: "/workspace/",
  getParentRoute: () => rootRoute,
} as any)

const IamIndexRoute = IamIndexImport.update({
  id: "/iam/",
  path: "/iam/",
  getParentRoute: () => rootRoute,
} as any)

const WorkspaceNewRoute = WorkspaceNewImport.update({
  id: "/workspace/new",
  path: "/workspace/new",
  getParentRoute: () => rootRoute,
} as any)

const WorkspaceContainersRoute = WorkspaceContainersImport.update({
  id: "/workspace/containers",
  path: "/workspace/containers",
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: "/auth/signup",
  path: "/auth/signup",
  getParentRoute: () => rootRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: "/auth/reset-password",
  path: "/auth/reset-password",
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: "/auth/forgot-password",
  path: "/auth/forgot-password",
  getParentRoute: () => rootRoute,
} as any)

const AuthActivateRoute = AuthActivateImport.update({
  id: "/auth/activate",
  path: "/auth/activate",
  getParentRoute: () => rootRoute,
} as any)

const WorkspaceWorkspaceIdIndexRoute = WorkspaceWorkspaceIdIndexImport.update({
  id: "/workspace/$workspaceId/",
  path: "/workspace/$workspaceId/",
  getParentRoute: () => rootRoute,
} as any)

const IamUsersIndexRoute = IamUsersIndexImport.update({
  id: "/iam/users/",
  path: "/iam/users/",
  getParentRoute: () => rootRoute,
} as any)

const WorkspaceWorkspaceIdSettingsRoute =
  WorkspaceWorkspaceIdSettingsImport.update({
    id: "/workspace/$workspaceId/settings",
    path: "/workspace/$workspaceId/settings",
    getParentRoute: () => rootRoute,
  } as any)

const WorkspaceWorkspaceIdPermissionsRoute =
  WorkspaceWorkspaceIdPermissionsImport.update({
    id: "/workspace/$workspaceId/permissions",
    path: "/workspace/$workspaceId/permissions",
    getParentRoute: () => rootRoute,
  } as any)

const IamUsersNewRoute = IamUsersNewImport.update({
  id: "/iam/users/new",
  path: "/iam/users/new",
  getParentRoute: () => rootRoute,
} as any)

const IamUsersUserIdRoute = IamUsersUserIdImport.update({
  id: "/iam/users/$userId",
  path: "/iam/users/$userId",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/auth/activate": {
      id: "/auth/activate"
      path: "/auth/activate"
      fullPath: "/auth/activate"
      preLoaderRoute: typeof AuthActivateImport
      parentRoute: typeof rootRoute
    }
    "/auth/forgot-password": {
      id: "/auth/forgot-password"
      path: "/auth/forgot-password"
      fullPath: "/auth/forgot-password"
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    "/auth/login": {
      id: "/auth/login"
      path: "/auth/login"
      fullPath: "/auth/login"
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    "/auth/reset-password": {
      id: "/auth/reset-password"
      path: "/auth/reset-password"
      fullPath: "/auth/reset-password"
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof rootRoute
    }
    "/auth/signup": {
      id: "/auth/signup"
      path: "/auth/signup"
      fullPath: "/auth/signup"
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    "/workspace/containers": {
      id: "/workspace/containers"
      path: "/workspace/containers"
      fullPath: "/workspace/containers"
      preLoaderRoute: typeof WorkspaceContainersImport
      parentRoute: typeof rootRoute
    }
    "/workspace/new": {
      id: "/workspace/new"
      path: "/workspace/new"
      fullPath: "/workspace/new"
      preLoaderRoute: typeof WorkspaceNewImport
      parentRoute: typeof rootRoute
    }
    "/iam/": {
      id: "/iam/"
      path: "/iam"
      fullPath: "/iam"
      preLoaderRoute: typeof IamIndexImport
      parentRoute: typeof rootRoute
    }
    "/workspace/": {
      id: "/workspace/"
      path: "/workspace"
      fullPath: "/workspace"
      preLoaderRoute: typeof WorkspaceIndexImport
      parentRoute: typeof rootRoute
    }
    "/iam/users/$userId": {
      id: "/iam/users/$userId"
      path: "/iam/users/$userId"
      fullPath: "/iam/users/$userId"
      preLoaderRoute: typeof IamUsersUserIdImport
      parentRoute: typeof rootRoute
    }
    "/iam/users/new": {
      id: "/iam/users/new"
      path: "/iam/users/new"
      fullPath: "/iam/users/new"
      preLoaderRoute: typeof IamUsersNewImport
      parentRoute: typeof rootRoute
    }
    "/workspace/$workspaceId/permissions": {
      id: "/workspace/$workspaceId/permissions"
      path: "/workspace/$workspaceId/permissions"
      fullPath: "/workspace/$workspaceId/permissions"
      preLoaderRoute: typeof WorkspaceWorkspaceIdPermissionsImport
      parentRoute: typeof rootRoute
    }
    "/workspace/$workspaceId/settings": {
      id: "/workspace/$workspaceId/settings"
      path: "/workspace/$workspaceId/settings"
      fullPath: "/workspace/$workspaceId/settings"
      preLoaderRoute: typeof WorkspaceWorkspaceIdSettingsImport
      parentRoute: typeof rootRoute
    }
    "/iam/users/": {
      id: "/iam/users/"
      path: "/iam/users"
      fullPath: "/iam/users"
      preLoaderRoute: typeof IamUsersIndexImport
      parentRoute: typeof rootRoute
    }
    "/workspace/$workspaceId/": {
      id: "/workspace/$workspaceId/"
      path: "/workspace/$workspaceId"
      fullPath: "/workspace/$workspaceId"
      preLoaderRoute: typeof WorkspaceWorkspaceIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/auth/activate": typeof AuthActivateRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/reset-password": typeof AuthResetPasswordRoute
  "/auth/signup": typeof AuthSignupRoute
  "/workspace/containers": typeof WorkspaceContainersRoute
  "/workspace/new": typeof WorkspaceNewRoute
  "/iam": typeof IamIndexRoute
  "/workspace": typeof WorkspaceIndexRoute
  "/iam/users/$userId": typeof IamUsersUserIdRoute
  "/iam/users/new": typeof IamUsersNewRoute
  "/workspace/$workspaceId/permissions": typeof WorkspaceWorkspaceIdPermissionsRoute
  "/workspace/$workspaceId/settings": typeof WorkspaceWorkspaceIdSettingsRoute
  "/iam/users": typeof IamUsersIndexRoute
  "/workspace/$workspaceId": typeof WorkspaceWorkspaceIdIndexRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/auth/activate": typeof AuthActivateRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/reset-password": typeof AuthResetPasswordRoute
  "/auth/signup": typeof AuthSignupRoute
  "/workspace/containers": typeof WorkspaceContainersRoute
  "/workspace/new": typeof WorkspaceNewRoute
  "/iam": typeof IamIndexRoute
  "/workspace": typeof WorkspaceIndexRoute
  "/iam/users/$userId": typeof IamUsersUserIdRoute
  "/iam/users/new": typeof IamUsersNewRoute
  "/workspace/$workspaceId/permissions": typeof WorkspaceWorkspaceIdPermissionsRoute
  "/workspace/$workspaceId/settings": typeof WorkspaceWorkspaceIdSettingsRoute
  "/iam/users": typeof IamUsersIndexRoute
  "/workspace/$workspaceId": typeof WorkspaceWorkspaceIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/auth/activate": typeof AuthActivateRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/reset-password": typeof AuthResetPasswordRoute
  "/auth/signup": typeof AuthSignupRoute
  "/workspace/containers": typeof WorkspaceContainersRoute
  "/workspace/new": typeof WorkspaceNewRoute
  "/iam/": typeof IamIndexRoute
  "/workspace/": typeof WorkspaceIndexRoute
  "/iam/users/$userId": typeof IamUsersUserIdRoute
  "/iam/users/new": typeof IamUsersNewRoute
  "/workspace/$workspaceId/permissions": typeof WorkspaceWorkspaceIdPermissionsRoute
  "/workspace/$workspaceId/settings": typeof WorkspaceWorkspaceIdSettingsRoute
  "/iam/users/": typeof IamUsersIndexRoute
  "/workspace/$workspaceId/": typeof WorkspaceWorkspaceIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/auth/activate"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/reset-password"
    | "/auth/signup"
    | "/workspace/containers"
    | "/workspace/new"
    | "/iam"
    | "/workspace"
    | "/iam/users/$userId"
    | "/iam/users/new"
    | "/workspace/$workspaceId/permissions"
    | "/workspace/$workspaceId/settings"
    | "/iam/users"
    | "/workspace/$workspaceId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/auth/activate"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/reset-password"
    | "/auth/signup"
    | "/workspace/containers"
    | "/workspace/new"
    | "/iam"
    | "/workspace"
    | "/iam/users/$userId"
    | "/iam/users/new"
    | "/workspace/$workspaceId/permissions"
    | "/workspace/$workspaceId/settings"
    | "/iam/users"
    | "/workspace/$workspaceId"
  id:
    | "__root__"
    | "/"
    | "/auth/activate"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/reset-password"
    | "/auth/signup"
    | "/workspace/containers"
    | "/workspace/new"
    | "/iam/"
    | "/workspace/"
    | "/iam/users/$userId"
    | "/iam/users/new"
    | "/workspace/$workspaceId/permissions"
    | "/workspace/$workspaceId/settings"
    | "/iam/users/"
    | "/workspace/$workspaceId/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthActivateRoute: typeof AuthActivateRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  WorkspaceContainersRoute: typeof WorkspaceContainersRoute
  WorkspaceNewRoute: typeof WorkspaceNewRoute
  IamIndexRoute: typeof IamIndexRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  IamUsersUserIdRoute: typeof IamUsersUserIdRoute
  IamUsersNewRoute: typeof IamUsersNewRoute
  WorkspaceWorkspaceIdPermissionsRoute: typeof WorkspaceWorkspaceIdPermissionsRoute
  WorkspaceWorkspaceIdSettingsRoute: typeof WorkspaceWorkspaceIdSettingsRoute
  IamUsersIndexRoute: typeof IamUsersIndexRoute
  WorkspaceWorkspaceIdIndexRoute: typeof WorkspaceWorkspaceIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthActivateRoute: AuthActivateRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  WorkspaceContainersRoute: WorkspaceContainersRoute,
  WorkspaceNewRoute: WorkspaceNewRoute,
  IamIndexRoute: IamIndexRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  IamUsersUserIdRoute: IamUsersUserIdRoute,
  IamUsersNewRoute: IamUsersNewRoute,
  WorkspaceWorkspaceIdPermissionsRoute: WorkspaceWorkspaceIdPermissionsRoute,
  WorkspaceWorkspaceIdSettingsRoute: WorkspaceWorkspaceIdSettingsRoute,
  IamUsersIndexRoute: IamUsersIndexRoute,
  WorkspaceWorkspaceIdIndexRoute: WorkspaceWorkspaceIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/activate",
        "/auth/forgot-password",
        "/auth/login",
        "/auth/reset-password",
        "/auth/signup",
        "/workspace/containers",
        "/workspace/new",
        "/iam/",
        "/workspace/",
        "/iam/users/$userId",
        "/iam/users/new",
        "/workspace/$workspaceId/permissions",
        "/workspace/$workspaceId/settings",
        "/iam/users/",
        "/workspace/$workspaceId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/activate": {
      "filePath": "auth/activate.tsx"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/reset-password": {
      "filePath": "auth/reset-password.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/workspace/containers": {
      "filePath": "workspace/containers.tsx"
    },
    "/workspace/new": {
      "filePath": "workspace/new.tsx"
    },
    "/iam/": {
      "filePath": "iam/index.tsx"
    },
    "/workspace/": {
      "filePath": "workspace/index.tsx"
    },
    "/iam/users/$userId": {
      "filePath": "iam/users/$userId.tsx"
    },
    "/iam/users/new": {
      "filePath": "iam/users/new.tsx"
    },
    "/workspace/$workspaceId/permissions": {
      "filePath": "workspace/$workspaceId/permissions.tsx"
    },
    "/workspace/$workspaceId/settings": {
      "filePath": "workspace/$workspaceId/settings.tsx"
    },
    "/iam/users/": {
      "filePath": "iam/users/index.tsx"
    },
    "/workspace/$workspaceId/": {
      "filePath": "workspace/$workspaceId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
