---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: aws-secrets
    namespace: bones
spec:
    provider:
        aws:
            service: SecretsManager
            region: us-east-1
            auth:
                jwt:
                    serviceAccountRef:
                        name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: bones-secrets
    namespace: bones
spec:
    refreshInterval: 1m
    secretStoreRef:
        name: aws-secrets
        kind: ClusterSecretStore
    target:
        name: bones-env
        template:
            type: Opaque
            data:
                .env: |
                    APP_URL={{ .APP_URL }}
                    CLIENT_URL={{ .CLIENT_URL }}
                    ENV={{ .ENV }}
                    PORT={{ .PORT }}
                    LOG_LEVEL={{ .LOG_LEVEL }}
                    COOKIE_ENCRYPTION_KEY={{ .COOKIE_ENCRYPTION_KEY }}
                    CORS_ORIGINS={{ .CORS_ORIGINS }}
                    DB_USERNAME={{ .DB_USERNAME }}
                    DB_PASSWORD={{ .DB_PASSWORD }}
                    DB_HOST={{ .DB_HOST }}
                    DB_PORT={{ .DB_PORT }}
                    DB_NAME={{ .DB_NAME }}
                    DB_MIGRATING={{ .DB_MIGRATING }}
                    DB_SEEDING={{ .DB_SEEDING }}
                    REDIS_HOST={{ .REDIS_HOST }}
                    REDIS_PORT={{ .REDIS_PORT }}
                    SMTP_HOST={{ .SMTP_HOST }}
                    SMTP_PORT={{ .SMTP_PORT }}
                    SMTP_USERNAME={{ .SMTP_USERNAME }}
                    SMTP_PASSWORD={{ .SMTP_PASSWORD }}
                    FROM_EMAIL={{ .FROM_EMAIL }}
                    ACCESS_TOKEN_SECRET={{ .ACCESS_TOKEN_SECRET }}
                    REFRESH_TOKEN_SECRET={{ .REFRESH_TOKEN_SECRET }}
                    ACCESS_TOKEN_AGE={{ .ACCESS_TOKEN_AGE }}
                    REFRESH_TOKEN_AGE={{ .REFRESH_TOKEN_AGE }}
                    REFRESH_TOKEN_AGE_IN_DATE={{ .REFRESH_TOKEN_AGE_IN_DATE }}
                    WORKSPACE_EXPOSED_PORTS={{ .WORKSPACE_EXPOSED_PORTS }}
                    WORKSPACE_DOMAIN_SUFFIX={{ .WORKSPACE_DOMAIN_SUFFIX }}
                    K8S_CLUSTER_API_URL={{ .K8S_CLUSTER_API_URL }}
    data:
        - secretKey: APP_URL
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: APP_URL
        - secretKey: CLIENT_URL
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: CLIENT_URL
        - secretKey: ENV
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: ENV
        - secretKey: PORT
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: PORT
        - secretKey: LOG_LEVEL
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: LOG_LEVEL
        - secretKey: COOKIE_ENCRYPTION_KEY
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: COOKIE_ENCRYPTION_KEY
        - secretKey: CORS_ORIGINS
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: CORS_ORIGINS
        - secretKey: DB_USERNAME
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: DB_USERNAME
        - secretKey: DB_PASSWORD
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: DB_PASSWORD
        - secretKey: DB_HOST
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: DB_HOST
        - secretKey: DB_PORT
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: DB_PORT
        - secretKey: DB_NAME
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: DB_NAME
        - secretKey: DB_MIGRATING
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: DB_MIGRATING
        - secretKey: DB_SEEDING
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: DB_SEEDING
        - secretKey: REDIS_HOST
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: REDIS_HOST
        - secretKey: REDIS_PORT
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: REDIS_PORT
        - secretKey: SMTP_HOST
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: SMTP_HOST
        - secretKey: SMTP_PORT
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: SMTP_PORT
        - secretKey: SMTP_USERNAME
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: SMTP_USERNAME
        - secretKey: SMTP_PASSWORD
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: SMTP_PASSWORD
        - secretKey: FROM_EMAIL
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: FROM_EMAIL
        - secretKey: ACCESS_TOKEN_SECRET
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: ACCESS_TOKEN_SECRET
        - secretKey: REFRESH_TOKEN_SECRET
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: REFRESH_TOKEN_SECRET
        - secretKey: ACCESS_TOKEN_AGE
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: ACCESS_TOKEN_AGE
        - secretKey: REFRESH_TOKEN_AGE
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: REFRESH_TOKEN_AGE
        - secretKey: REFRESH_TOKEN_AGE_IN_DATE
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: REFRESH_TOKEN_AGE_IN_DATE
        - secretKey: WORKSPACE_EXPOSED_PORTS
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: WORKSPACE_EXPOSED_PORTS
        - secretKey: WORKSPACE_DOMAIN_SUFFIX
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: WORKSPACE_DOMAIN_SUFFIX
        - secretKey: K8S_CLUSTER_API_URL
          remoteRef:
              key: arn:aws:secretsmanager:us-east-1:<account-id>:secret:staging-app-secrets-final-<secret-arn-end-string>
              property: K8S_CLUSTER_API_URL
