---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: external-secrets-sa
    namespace: bones
    labels:
        app.kubernetes.io/managed-by: Helm
    annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/external-secrets-role
        meta.helm.sh/release-name: external-secrets
        meta.helm.sh/release-namespace: bones
